---
title: "R Notebook"
output: html_notebook
---

```{r}
rm(list=ls())
```

# Library

```{r include=FALSE}
library(tidyverse)
library(tidymodels)
library(glmnet)
library(themis)
library(vip)
```

# Load data

```{r}
load("ML_Data.RData")
```

# 1. Set up recipe

```{r}
recipe_ridge <- recipe(AAER ~ ., data = dfTrain) %>%
  update_role(companyid, keydevid, transcriptid, headline, year, quarter, cik, new_role = "metadata") %>%
  step_dummy(all_nominal_predictors()) %>%
  step_normalize(all_numeric_predictors()) %>%
  step_downsample(AAER, under_ratio = 1, seed = 599) %>%
  update_role(Topic_01, Topic_02, Topic_03, Topic_04, Topic_05, Topic_06, Topic_07, Topic_08, Topic_09, Topic_10, Topic_11, Topic_12, Topic_13, Topic_14, Topic_15, Topic_16, Topic_17, Topic_18, Topic_19, Topic_20, Topic_21, Topic_22, Topic_23, Topic_24, Topic_25, Topic_26, Topic_27, Topic_28, Topic_29, Topic_30, Topic_31, Topic_32, Topic_33, Topic_34, Topic_35, Topic_36, Topic_37, Topic_38, Topic_39, Topic_40, new_role = "dont_use")
```

# 2. Set up model

```{r}
ridge <- logistic_reg(penalty=tune(), mixture=0) %>%
  set_engine("glmnet")
```

# 3. Combine into workflow

```{r}
ridge_tune_wf <- workflow() %>% 
  add_recipe(recipe_ridge) %>% 
  add_model(ridge)
```

# 4. Set metrics

Set metrics
```{r}
class_metrics <- metric_set(accuracy, sensitivity, specificity, roc_auc)
```

# 5. Set parameters for tuning

```{r}
grid_ridge <- tibble(penalty = 10^(seq(from = -3, to = 3, length.out = 250)))
```

# 6. Run tuning

```{r}
ridge_tune <- ridge_tune_wf %>% 
  tune_grid(resamples=cv_folds,
            grid=grid_ridge, 
            metrics=class_metrics)
```

# 7. Plot tuning result

```{r}
ridge_tune_metrics <- ridge_tune %>% collect_metrics()
ridge_tune_metrics

```

```{r}
ridge_tune_metrics %>%
  filter(.metric %in% c("roc_auc", "accuracy", "sensitivity","specificity")) %>%
  ggplot(aes(x = penalty, y = mean, ymin = mean - std_err, ymax = mean + std_err, 
             colour = .metric)) +
  geom_line() +
  geom_point() +
  scale_x_log10() + 
  facet_grid(.metric ~ ., scales = "free_y") 
```


# 8. Select best parameter

```{r}
ridge_best <- ridge_tune %>% 
  select_best(metric = "roc_auc")
ridge_best
```

# 9. Finalized workflow

```{r}
ridge_final_wf <- ridge_tune_wf %>% finalize_workflow(ridge_best)
ridge_final_wf
```

# 10. Performance on test set

```{r}
ridge_final_fit <- ridge_final_wf %>% 
  last_fit(split, metrics = class_metrics)

ridge_final_fit %>% collect_metrics()
```

```{r}
ridge_final_fit %>% collect_predictions() %>% 
  conf_mat(truth = AAER, estimate = .pred_class) 
```

# 11. Variable importance score

```{r}
ridge_vi <- logistic_reg(penalty=ridge_best$penalty, mixture=0) %>%
  set_engine("glmnet", importance = "permutation")

ridge_vi_wf <- workflow() %>% 
  add_model(ridge_vi) %>% 
  add_recipe(recipe_ridge)

ridge_vi_fit <- ridge_vi_wf %>% 
  fit(data = dfTrain)

ridge_vi_fit %>% extract_fit_parsnip() %>% vi()

ridge_vi_fit %>% extract_fit_parsnip() %>% vip(geom = "point", num_features = 10)

```